In [7]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv(r"DatasetAnalysis_csv.csv")

In [9]:
data

,battery_power,clock_speed,fc,int_memory,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,blue,dual_sim,four_g,three_g,touch_screen,wifi,price_range
0,842,2.2,1,7,188,2,2,20,756,2549,9,7,19,0,0,0,0,0,1,1
1,1021,0.5,0,53,136,3,6,905,1988,2631,17,3,7,1,1,1,1,1,0,2
2,563,0.5,2,41,145,5,6,1263,1716,2603,11,2,9,1,1,1,1,1,0,2
3,615,2.5,0,10,131,6,9,1216,1786,2769,16,8,11,1,0,0,1,0,0,2
4,1821,1.2,13,44,141,2,14,1208,1212,1411,8,2,15,1,0,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,0.5,0,2,106,6,14,1222,1890,668,13,4,19,1,1,1,1,1,0,0
1996,1965,2.6,0,39,187,4,3,915,1965,2032,11,10,16,1,1,0,1,1,1,2
1997,1911,0.9,1,36,108,8,3,868,1632,3057,9,1,5,0,1,1,1,1,0,3
1998,1512,0.9,4,46,145,5,5,336,670,869,18,10,19,0,0,1,1,1,1,0
1999,510,2.0,5,45,168,6,16,483,754,3919,19,4,2,1,1,1,1,1,1,3

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaled = MinMaxScaler()

In [13]:
data.columns

Index(['battery_power', 'clock_speed', 'fc', 'int_memory', 'mobile_wt',
       'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w',
       'talk_time', 'blue', 'dual_sim', 'four_g', 'three_g', 'touch_screen',
       'wifi', 'price_range'],
      dtype='object')

In [17]:
data_scaled = scaled.fit_transform(data[['battery_power', 'clock_speed', 'fc', 'int_memory', 'mobile_wt','n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w','talk_time']])

In [22]:
data_scaled = pd.DataFrame(data_scaled)

In [23]:
data_scaled

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.227789,0.68,0.052632,0.080645,0.900000,0.142857,0.10,0.010204,0.170895,0.612774,0.285714,0.388889,0.944444
1,0.347361,0.00,0.000000,0.822581,0.466667,0.285714,0.30,0.461735,0.993324,0.634687,0.857143,0.166667,0.277778
2,0.041416,0.00,0.105263,0.629032,0.541667,0.571429,0.30,0.644388,0.811749,0.627205,0.428571,0.111111,0.388889
3,0.076152,0.80,0.000000,0.129032,0.425000,0.714286,0.45,0.620408,0.858478,0.671566,0.785714,0.444444,0.500000
4,0.881764,0.28,0.684211,0.677419,0.508333,0.142857,0.70,0.616327,0.475300,0.308658,0.214286,0.111111,0.722222
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.195725,0.00,0.000000,0.000000,0.216667,0.714286,0.70,0.623469,0.927904,0.110102,0.571429,0.222222,0.944444
1996,0.977956,0.84,0.000000,0.596774,0.891667,0.428571,0.15,0.466837,0.977971,0.474613,0.428571,0.555556,0.777778
1997,0.941884,0.16,0.052632,0.548387,0.233333,1.000000,0.15,0.442857,0.755674,0.748530,0.285714,0.055556,0.166667
1998,0.675351,0.16,0.210526,0.709677,0.541667,0.571429,0.25,0.171429,0.113485,0.163816,0.928571,0.555556,0.944444
1999,0.006012,0.60,0.263158,0.693548,0.733333,0.714286,0.80,0.246429,0.169559,0.978888,1.000000,0.222222,0.000000

In [24]:
data_scaled[['blue', 'dual_sim', 'four_g', 'three_g', 'touch_screen','wifi', 'price_range']] = data[['blue', 'dual_sim', 'four_g', 'three_g', 'touch_screen','wifi', 'price_range']]

In [25]:
data_scaled

,0,1,2,3,4,5,6,7,8,9,10,11,12,blue,dual_sim,four_g,three_g,touch_screen,wifi,price_range
0,0.227789,0.68,0.052632,0.080645,0.900000,0.142857,0.10,0.010204,0.170895,0.612774,0.285714,0.388889,0.944444,0,0,0,0,0,1,1
1,0.347361,0.00,0.000000,0.822581,0.466667,0.285714,0.30,0.461735,0.993324,0.634687,0.857143,0.166667,0.277778,1,1,1,1,1,0,2
2,0.041416,0.00,0.105263,0.629032,0.541667,0.571429,0.30,0.644388,0.811749,0.627205,0.428571,0.111111,0.388889,1,1,1,1,1,0,2
3,0.076152,0.80,0.000000,0.129032,0.425000,0.714286,0.45,0.620408,0.858478,0.671566,0.785714,0.444444,0.500000,1,0,0,1,0,0,2
4,0.881764,0.28,0.684211,0.677419,0.508333,0.142857,0.70,0.616327,0.475300,0.308658,0.214286,0.111111,0.722222,1,0,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.195725,0.00,0.000000,0.000000,0.216667,0.714286,0.70,0.623469,0.927904,0.110102,0.571429,0.222222,0.944444,1,1,1,1,1,0,0
1996,0.977956,0.84,0.000000,0.596774,0.891667,0.428571,0.15,0.466837,0.977971,0.474613,0.428571,0.555556,0.777778,1,1,0,1,1,1,2
1997,0.941884,0.16,0.052632,0.548387,0.233333,1.000000,0.15,0.442857,0.755674,0.748530,0.285714,0.055556,0.166667,0,1,1,1,1,0,3
1998,0.675351,0.16,0.210526,0.709677,0.541667,0.571429,0.25,0.171429,0.113485,0.163816,0.928571,0.555556,0.944444,0,0,1,1,1,1,0
1999,0.006012,0.60,0.263158,0.693548,0.733333,0.714286,0.80,0.246429,0.169559,0.978888,1.000000,0.222222,0.000000,1,1,1,1,1,1,3

In [30]:
data_scaled.rename(columns={0:'battery_power', 1:'clock_speed', 2:'fc', 3:'int_memory', 4:'mobile_wt',5:'n_cores', 6:'pc', 7:'px_height', 8:'px_width', 9:'ram',10: 'sc_h',11:'sc_w',12:'talk_time'},inplace=True)

In [31]:
data_scaled.to_csv("ScaledDataSet.csv",index=False)